kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: konfig-syncer
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["secrets", "configmaps"]
    verbs: ["get", "watch", "list", "update", "patch", "delete", "create"]
  - apiGroups: [""] # "" indicates the core API group
    resources: ["namespaces"]
    verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: konfig-syncer
roleRef:
  kind: ClusterRole
  name: konfig-syncer
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: konfig-syncer
    namespace: kube-system
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: konfig-syncer
  namespace: kube-system
